Remove side-effects from `main`
ergoplatform/oracle-core pull request #41
Opened 2022-05-27 15:02 UTC by kettlebell

Close #40

2022-06-01 05:29 UTC, kettlebell commented on core/src/main.rs
> +    //    .name("Oracle Core GET API Thread".to_string())
I think we can do away with the `api` module directly. What do you think?

2022-06-01 05:32 UTC, kettlebell commented
Fixed up `main.rs`. In addition, I fixed some bugs in parsing the boostrap YAML file and sprinkled some logging statements in.

2022-06-01 15:56 UTC, greenhat requested changes
Looking great! Thank you! Let's keep local REST API running for now.

2022-06-02 15:19 UTC, kettlebell commented on core/src/main.rs
> +    //    .name("Oracle Core GET API Thread".to_string())
Sure. The API instantiates instances of `OraclePool` which means it needs an existing oracle pool YAML config file. Therefore it makes sense to move it under the CLI `Command::Run` as I've done with the latest commit.

2022-06-03 11:42 UTC, greenhat approved these changes
Thank you!

2022-06-03 11:43 UTC, merged