Add commit hash to oracle-core version
ergoplatform/oracle-core pull request #46
Opened 2022-06-08 17:48 UTC by SethDusek

2022-08-03 14:28 UTC, greenhat commented
@SethDusek I feel like I'm waiting for you to mark it as ready while it actually was ready a long time ago. :) Is it the case?

2022-08-04 00:58 UTC, SethDusek commented
Yup, I actually forgot about this PR for a while. It should be good to go

2022-08-04 07:30 UTC, greenhat requested changes
Looking great! Just a tiny note.

2022-08-04 07:30 UTC, greenhat commented on core/src/main.rs
> +const ORACLE_VERSION: &str = concat!(
I think `APP_VERSION` or even `VERSION` would be a better name since we don't have any other versions.

2022-08-08 05:20 UTC, greenhat approved these changes
Great! Thank you!

2022-08-08 05:20 UTC, merged