Add Update Contract
ergoplatform/oracle-core pull request #60
Opened 2022-06-20 11:16 UTC by SethDusek

Hi, I've added the update contract. 

I had some questions regarding the PR though
- What is the best way to obtain the index for a certain constant? Right now the way I used is to just print all the constants, and see which one matches the constant in the source code for update contract. 
- Is submitting to chain/unit testing similar to core/pool_commands/refresh.rs part of this issue?

2022-06-20 11:34 UTC, greenhat commented
> Hi, I've added the update contract for #51

Great! Thank you!

> 
> I had some questions regarding the PR though
> 
>     * What is the best way to obtain the index for a certain constant? Right now the way I used is to just print all the constants, and see which one matches the constant in the source code for update contract.

I'm using the same technique and I'm unaware of a better way to do it. There is an EIP for named constant support for the compiler but it's not implemented.

> 
>     * Is submitting to chain/unit testing similar to core/pool_commands/refresh.rs part of this issue?

I'm not sure I understand the question. The submission (update command after voting) should be implemented in #49. This (#51) issue is just for the contract parametrization in the `contracts` module.

2022-06-21 11:22 UTC, SethDusek commented
> I'm using the same technique and I'm unaware of a better way to do it. There is an EIP for named constant support for the compiler but it's not implemented.

Hmm, if ergoscript-compiler (from sigma-rust) is mature enough maybe that could be used to compile it. That way we could also have the source code for contracts part of the contract itself instead of obtaining the compiled version from Playground. If there's some way to inspect the AST we could maybe use that to obtain constant indexes too, but I'm not too familiar with ergoscript-compiler's inner workings

2022-06-22 15:10 UTC, greenhat commented
> > I'm using the same technique and I'm unaware of a better way to do it. There is an EIP for named constant support for the compiler but it's not implemented.
> 
> Hmm, if ergoscript-compiler (from sigma-rust) is mature enough maybe that could be used to compile it. That way we could also have the source code for contracts be part of the UpdateContract/PoolContract/etc itself instead of obtaining the compiled version from Playground. 

ergoscript-compiler is roughly 0.5% ready, so no, but it'd be great to have the contract's ErgoScript code along with the off-chain code.

> If there's some way to inspect the AST we could maybe use that to obtain constant indexes too, but I'm not too familiar with ergoscript-compiler's inner workings

Constant indices are built during the serialization of an AST where constants are swapped with placeholders with an index. I cannot think of any AST analysis that would help here.

Here is the EIP-5 I mentioned earlier - https://github.com/ergoplatform/eips/blob/master/eip-0005.md . Unfortunately, it's not been implemented yet.

2022-06-23 05:15 UTC, SethDusek commented
Yup, it's good to go

2022-06-23 07:51 UTC, greenhat requested changes
Looking good! Please, use the updated v2.0a version of the contract (see my comment).

2022-06-23 07:51 UTC, greenhat commented on core/src/contracts/update.rs
> +    // from https://wallet.plutomonkey.com/p2s/?source=eyAvLyBUaGlzIGJveCAodXBkYXRlIGJveCk6CiAgLy8gUmVnaXN0ZXJzIGVtcHR5IAogIC8vIAogIC8vIGJhbGxvdCBib3hlcyAoSW5wdXRzKQogIC8vIFI0IHRoZSBwdWIga2V5IG9mIHZv
There is an updated v2.0a version of the update box contract at https://github.com/scalahub/OraclePool/blob/58726e7751b2ff454ce4b3f45315f3cd549c2994/src/main/scala/oraclepool/v2a/Contracts.scala#L213-L270

2022-06-23 14:45 UTC, merged