Lock Update NFT in UpdateContract Box
ergoplatform/oracle-core pull request #70
Opened 2022-06-28 09:07 UTC by SethDusek

For #50

2022-06-30 09:55 UTC, SethDusek commented
Not sure what's up with the code coverage test. Did I mess something up while merging?

2022-06-30 14:25 UTC, greenhat commented
> Not sure what's up with the code coverage test. Did I mess something up while merging?

Nope. coveralls.io was down. I restarted the job.

2022-06-30 22:21 UTC, SethDusek commented
Thanks! Anyways, this PR should be good to go now. I've also modified the tests a bit so we can inspect the bootstrap transactions in unit tests and make sure everything is as it should be. Right now I'm just checking for the right parameters in the update contract though

2022-07-01 08:58 UTC, greenhat commented
Could you please rebase? Probably one of the recently merged PRs caused the conflict.

2022-07-01 11:39 UTC, SethDusek commented
Done! The new tests actually caught a mistake I made in the commit, which I think is pretty neat

2022-07-04 11:23 UTC, greenhat requested changes
Looking great! I appreciate the test! Just one minor request.

2022-07-04 11:23 UTC, greenhat commented on core/src/contracts/update.rs
> +    pub ergo_tree: ErgoTree,
Could you please add a getter for `ergo_tree` property like in other contracts? I'm still not sure if we'll keep `ErgoTree` or generate it on request, so it's better to keep it private.

2022-07-05 05:45 UTC, greenhat approved these changes
Great! Thank you!

2022-07-05 05:45 UTC, merged